### ISSUE TITLE
Bukkit Gui error (Not Starting)

### ISSUE THREAD

**Issue by iJDuhb** [Bertware/bukkitgui2#109]
Bukkit gui not loading up...
Java 8 update 66
64-bit
Windows 10

Error:
The application encountered an unexpected error!
Please contact the developer with the following information:
Exception: Object reference not set to an instance of an object.
Details:  at
Net.Bertware.Bukkitgui2.Core.Configuration.Config.ReadString(String parent, String key, String defaultValue)
  at Net.Bertware.Bukkitgui2.Core.Locale.Initialize()
  at Net.Bertware.Bukkitgui2.Core.Share.Initialize()
  at Net.Bertware.Bukkitgui2.UI,MainForm..ctor()
  at Net.Bertware.Bukkitgui2.Launcher.Run()
  at Net.Bertware.Bukkitgui2.Program.Main(String[] argStrings)

Please fix this issue!

**Comment by Bertware** [comment]
Can you try deleting %appdata%\Bertware\Bukkitgui2\config\config.xml ?

**Comment by iJDuhb** [comment]
Ok

**Comment by iJDuhb** [comment]
I'm in now whenever I try to start server it says "Could not start server       The java path could not be found, server start aborted Please select the correct java version in the superstart tab"
And I am using correct version... I checked.

**Comment by Bertware** [comment]
Try the different java versions. If it shows up, it's detected, and it should be okay. Java should be installed in the default install location, and should be JRE 7 or higher.

**Comment by iJDuhb** [comment]
I got it... thanks for the help, I really appreciated it! :))!!

**Comment by Bertware** [comment]
Glad it's fixed :)
