### ISSUE TITLE
it says this when i click launch server look in the description

### ISSUE THREAD

**Issue by RebelsForDeath** [Bertware/bukkitgui2#113]
10:30:58 PM [GUI] Starting server...
10:30:59 PM Loading BuildTools version: git-BuildTools-afc7566-52 (#52)
10:30:59 PM Exception in thread "main" joptsimple.UnrecognizedOptionException: 'n' is not a recognized option
10:30:59 PM at joptsimple.OptionException.unrecognizedOption(OptionException.java:89)
10:30:59 PM [GUI] The server has stopped

I don't know what is that plz  help send me on this account on gmail ammaryassermessi@gmail.com

with my best wishes

**Comment by Bertware** [comment]
You are running builtools instead of a valid server. Use a valid server file instead of builtools.jar.
