### ISSUE TITLE
Bukkit GUI wont even open

### ISSUE THREAD

**Issue by ZDavePlays** [Bertware/bukkitgui2#114]
i downloaded the latest version of Bukkit GUI and i put it on a folder, then open it, it doenst open, it just open a tab like this:

![838e1859c2db0848f6126661c0923268](https://cloud.githubusercontent.com/assets/20375349/16711014/21d3ed38-460c-11e6-97ba-f3af10983a53.png)

even tough the picture say it may take several minutes it takes 2 seconds

i try with every version of Bukkit GUI from 1.8 to 1.9! please help me!

**Comment by Bertware** [comment]
You propbably need the .NET framework.

http://download.microsoft.com/download/6/0/f/60fc5854-3cb8-4892-b6db-bd4f42510f28/dotnetfx35.exe

If that doesn't work, delete the "%appdata%/bertware" folder on your system
