### ISSUE TITLE
Bukkitgui V2.0.0.335 Port Forward  Glitch or bug

### ISSUE THREAD

**Issue by Keeron1** [Bertware/bukkitgui2#116]
Hey I am trying to Port Forward  when I try to port forward let me show you what it says http://prnt.sc/c7lwvv that is what it says I tryed changing another to another ip or tcp or udp but I can't click the stop button help me a lot thank you a lot for writing.

**Comment by Bertware** [comment]
This means your router is not supported. Your router needs to support uPnpfor this, and uPnp needs to be enabled for this function to work.
