### ISSUE TITLE
BukkitGUI Wont start please help quick!

### ISSUE THREAD

**Issue by williebird** [Bertware/bukkitgui2#118]
Hello I started my BukkitGUI server and it said
The server.jar file you entered is invalid or corrupted Re-Download the file and try again

Please I would love a reply soon on how to fix this
## 

Thanks

**Comment by Bertware** [comment]
As the error message states, you need to download a minecraft server (vanilla, bukkit, ... ) which is downloaded as a .jar file. Point the GUI to this file in the start tab.
