### ISSUE TITLE
Fix Gui Not Starting

### ISSUE THREAD

**Issue by Guintz56** [Bertware/bukkitgui2#121]
![untitled](https://cloud.githubusercontent.com/assets/24538780/21129564/49752e9a-c13d-11e6-9c62-588b00574436.png)
Yow How to Fix This Its so Annoying

**Comment by Bertware** [comment]
Yow How about Some More Information lack Of Information is So annoying?

* Try putting your maximum ram to a value below 1500.
* Try changing the java installation (java version) being used.
* Try changing the server type.
