### ISSUE TITLE
Major Plugin Error

### ISSUE THREAD

**Issue by xXRedWolfXx** [Bertware/bukkitgui2#123]
Version 1.8.0.551

When i go to the plugin tab to install a plugin i get this. 
![1](https://cloud.githubusercontent.com/assets/25289477/22189125/90da082e-e112-11e6-96c5-5ebfc603e1f6.PNG)

And when i check the current plugins (all i have is Worldedit atm) for updates it fails to fetch any data
![2](https://cloud.githubusercontent.com/assets/25289477/22189134/a4c00f14-e112-11e6-9590-5b5faa8537b8.PNG)

Is bukkit GUI dead or is there a fatal error somewhere?

**Comment by Bertware** [comment]
bukget.org, the external service this feature relied on, shut down. Therefore this feature won't work anymore.
Thanks for bringing this to my attention.
