### ISSUE TITLE
Running as admin.

### ISSUE THREAD

**Issue by Waved123** [Bertware/bukkitgui2#128]
Someone wanna tell me how to run bukketgui as admin? Says I need to. Thanks

**Comment by Xdarkwolf33** [comment]
right click and click Run as Administrator

**Comment by Bertware** [comment]
See also:
http://www.digitalcitizen.life/how-run-programs-administrator-windows-7
https://technet.microsoft.com/en-us/library/ff431742.aspx

Note: you can also prevent running as administrator, by putting all files in (a subfolder of) your user account folder (C:/users/<your user name>/).
