### ISSUE TITLE
1.12 Not catching errors

### ISSUE THREAD

**Issue by peanutbutterk4** [Bertware/bukkitgui2#130]
I am not a pro but when I updated my server to Spigot 1.12 it stopped catching errors and putting them into the Error Logging section. When I see errors in the console they now say 'time main WARN' instead of 'time [WARN]' like they used too. That probably just needs to be changed. Also I am using version 1.8.0.551 and yes I know there is version 2.

**Comment by NorthWestTrees** [comment]
Hey peanutbutter, I have the same version of the program 1.8.0.551 and my GUI is working fine, maybe over view, your check boxes in the error log tab make sure they are not checked, also if all else fails to go to the info tab way at the far right and hit (Reset all settings) that may fix it.
