### ISSUE TITLE
Failed to Initialize on Windows XP Pro SP2

### ISSUE THREAD

**Issue by DjAlEx234** [Bertware/bukkitgui2#132]
When I try to run Bukkit GUI 1.8.0.551 Windows XP gives me an error message saying:
"The application failed to initialize properly (0xc0000135). Click on OK to terminate the application."
I have no idea whats going on. (It's a fresh install)

System Specs:
Pentium 4, 3 Ghz
512 MB of RAM

**Comment by DjAlEx234** [comment]
Wrong Version...

**Comment by DjAlEx234** [comment]
Has the same exact issue with BukkitGUI 2

**Comment by simon816** [comment]
1. Don't use XP (seriously you need to update)
2. At least install the latest service pack, and maybe even the unofficial SP4

As for the actual error, install ".NET framework" (I think v3.5 or v4.0 will work)

**Comment by Bertware** [comment]
You need at least .NET 4.0: 
- V3.5 including all previous versions: http://download.microsoft.com/download/6/0/f/60fc5854-3cb8-4892-b6db-bd4f42510f28/dotnetfx35.exe
- V4.5 including v4: https://www.microsoft.com/en-US/download/details.aspx?id=42642

**Comment by DjAlEx234** [comment]
@simon816 im using windows xp because i dont have any windows 7 disks, and i was planning on installing .net at some point

**Comment by DjAlEx234** [comment]
@simon816 do you have any windows xp sp4 download links?

**Comment by simon816** [comment]
@DjAlEx234 https://ryanvm.net/forum/viewtopic.php?f=5&t=10321&sid=9ca5c152b792aa41fcc3509abf460bc8
