### ISSUE TITLE
Error: Invalid or corrupt jarfile (JarFileLocation) & Plugins not showing

### ISSUE THREAD

**Issue by LeoTanaka2243** [Bertware/bukkitgui2#137]
I'm running Minecraft Server from this GUI. And I have some issues with it.
General: I do not see any available plugins in the "Install Plugins" tab under the "Plugins" tab. It shows "Error while loading plugins. Probably the server could not be reached." "You can right click and try refreshing." "If you selected a category, it's possible that this category is empty" which I have not. I needed to manually download jar files and then run the server to let Plugin file open.
Spogit: Also, an error occurs when I try to run Spogit file under Server type: Spigot and shows this "Error: Invalid or corrupt jarfile C:\Users...spigot-1.15.1.jar (File Location)" which shows when i open from run.bat file too. 
`java -Xmx10G -Xms10G -jar spogit.jar`
`pause`
while spogit jar file name is spogit.jar

I am using Minecraft 1.15.1. Bukkit Jar is working but not Spogit as stated. I am running on bad laptop Intel Core i3-5010U, Intel HD Graphics 5500, 16GB DDR3 RAM. Though I do not think these problems are system problems. The BukkitGUI version is v1.8.0.551
I was running a Bukkit server normally without GUI.
I have never tried with Vanilla, Remote JSONAPI, Generic Java. Java Version cannot be found unless through "Alternative java path" And every time when I launch server "Your Current bukkit version couldn't be determined" shows up which I was ignoring.

Waiting for Reply, Thank you

**Comment by RadCraftplay** [comment]
Plugin list used to be fetched from Bukkit API. Few years ago, it became paid. Since this project has been abadoned, probably no one would pay for it

About that spigot issue you are having... I could help you with that, but I would have to test it on my own PC. Recently, I'm very busy so few weekc might pass before I even start investigating your problem

**Comment by Bertware** [comment]
Bukget, the bukkit plugin API, has shut down: http://bukget.org/ . The plugin manager will therefore ease to work.

Regarding the spigot issue, something seems to be wrong with the jar file, can't help with that.
