### ISSUE TITLE
Question: When starting the server, it still pops up the cold vanilla minecraft server GUI, and -nogui doesn't work to get rid of it. How do I make it so that the old Vanilla GUI doesn't pop up?

### ISSUE THREAD

**Issue by GGGamesDevMain** [Bertware/bukkitgui2#138]

**Comment by Bragadeesh-Sankar** [comment]
Go to Starter tab and type "nogui" without " in the optional flags this will solve your problem

**Comment by Plasman888** [comment]
when i do that
'5:56:00 AM [GUI] Starting server...
5:56:00 AM Nov 04, 2020 5:56:00 AM org.bukkit.craftbukkit.Main main
5:56:00 AM SEVERE: n is not a recognized option
5:56:00 AM Option                                  Description
5:56:00 AM ------                                  -----------
5:56:00 AM -?, --help                              Show the help
5:56:00 AM -C, --commands-settings <File: Yml      File for command settings (default:
5:56:00 AM file>                                   commands.yml)
5:56:00 AM -P, --plugins <File: Plugin directory>  Plugin directory to use (default:
5:56:00 AM plugins)
5:56:00 AM -W, --universe, --world-container, --   World container (default: .)
5:56:00 AM world-dir <File: Directory
5:56:00 AM containing worlds>
5:56:00 AM -b, --bukkit-settings <File: Yml file>  File for bukkit settings (default:
5:56:00 AM bukkit.yml)
5:56:00 AM -c, --config <File: Properties file>    Properties file to use (default:
5:56:00 AM server.properties)
5:56:00 AM -d, --date-format <SimpleDateFormat:    Format of the date to display in the
5:56:00 AM Log date format>                        console (for log entries)
5:56:00 AM --demo                                  Demo mode
5:56:00 AM --eraseCache                            Whether to force cache erase during
5:56:00 AM world upgrade
5:56:00 AM --forceUpgrade                          Whether to force a world upgrade
5:56:00 AM -h, --host, --server-ip <String:        Host to listen on
5:56:00 AM Hostname or IP>
5:56:00 AM --log-append <Boolean: Log append>      Whether to append to the log file
5:56:00 AM (default: true)
5:56:00 AM --log-count <Integer: Log count>        Specified how many log files to cycle
5:56:00 AM through (default: 1)
5:56:00 AM --log-limit <Integer: Max log size>     Limits the maximum size of the log
5:56:00 AM file (0 = unlimited) (default: 0)
5:56:00 AM --log-pattern <String: Log filename>    Specfies the log filename pattern
5:56:00 AM (default: server.log)
5:56:00 AM --log-strip-color                       Strips color codes from log file
5:56:00 AM --noconsole                             Disables the console
5:56:00 AM [GUI] The server has stopped
'
this pops up

**Comment by Plasman888** [comment]
but if you put " nogui" it works
