### ISSUE TITLE
Only Java 32 Bit?

### ISSUE THREAD

**Issue by JasonBourne007** [Bertware/bukkitgui2#139]
I just downloaded BukkitGUI v2.0.0.335 and it is only showing "Java 8 - 32 Bit" for the Java version but I have triple checked that my system as well as my java version are both 64 bit. Is BukkitGUI v2 only 32 Bit?

**Comment by Bertware** [comment]
Seems like only the 32 bit java version is detected, this might have to do with non-standard file paths. You should be able to configure the java path yourself somehow. It's an old piece of software and looking back there is much that could have been implemented in a better, more robust way.
