### ISSUE TITLE
New task triggers menu items duplicate

### ISSUE THREAD

**Issue by technoguy20000** [Bertware/bukkitgui2#25]
![untitled](https://cloud.githubusercontent.com/assets/9159734/5599342/7680fec0-928a-11e4-8ed1-ca696b903c89.png)
"Server Cpu usage" is listed twice, and while some of the entries have spaces between words, others do not. Also worth mentioning that the new task window is not displayed in the task bar, making it hard to get back to it if you navigate to another window. A solution would be to set the always on top property to true.

**Comment by Bertware** [comment]
Thanks for the input, btw :)
