### ISSUE TITLE
32557MB or more of memory can not be specified.

### ISSUE THREAD

**Issue by cloud5414** [Bertware/bukkitgui2#33]
.net Framework originalmassage.
---
************** 例外テキスト **************
System.OverflowException: Int16 型の値が大きすぎるか、または小さすぎます。
   場所 System.Decimal.ToInt16(Decimal value)
   場所 Net.Bertware.Bukkitgui2.AddOn.Starter.StarterTab.NumMinRam_ValueChanged(Object sender, EventArgs e)
   場所 System.Windows.Forms.NumericUpDown.OnValueChanged(EventArgs e)
   場所 System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   場所 Net.Bertware.Bukkitgui2.AddOn.Starter.StarterTab.TbMinRamScroll(Object sender, EventArgs e)
   場所 MetroFramework.Controls.MetroTrackBar.OnValueChanged()
   場所 MetroFramework.Controls.MetroTrackBar.OnMouseMove(MouseEventArgs e)
   場所 System.Windows.Forms.Control.WmMouseMove(Message& m)
   場所 System.Windows.Forms.Control.WndProc(Message& m)
   場所 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Bertware** [comment]
Make sure you're using the latest version (http://dev.bukkit.org/media/files/851/445/bukkitgui.exe), this issue was resolved a while ago

**Comment by cloud5414** [comment]
There is no problem in bukkitgui.exe.
If the minimum memory of slider of starter tab to more than 32GB in bukkitgui2.exe,
This error will be displayed.

![81fe21b731156f836bdc744667466968](https://cloud.githubusercontent.com/assets/6592144/5645128/ee667410-96ae-11e4-955c-f114f2a3ef59.png)

**Comment by Bertware** [comment]
Please update to v2.0.0.224

**Comment by cloud5414** [comment]
I'm sorry, I did not have to see well.
Thanks you.　:D
