### ISSUE TITLE
UiLauncher window

### ISSUE THREAD

**Issue by technoguy20000** [Bertware/bukkitgui2#41]
A window that is hidden from the taskbar called UiLauncher simply displays Bukkitgui is running. Could this be left over from something or is this intentional?
![uilauncher](https://cloud.githubusercontent.com/assets/9159734/5692218/e10b5b50-98b1-11e4-9e49-4c38fc6c043d.png)

**Comment by Bertware** [comment]
It's intentional, it's a workaround for issues with the metro design, it shouldn't show up in the taskbar
