### ISSUE TITLE
Custom Name in Title Bar

### ISSUE THREAD

**Issue by cdsquirrel** [Bertware/bukkitgui2#43]
I would love to have the title bar be customizable. BG ver 1.7.x  would allow you to change the file name and it would reflect in the title bar. I have several instances running on my machine and i can not tell them apart with 2.0.x.

Possible changes.

1. Custom File name reflected in title bar
2. server config file variable for server-name, level-name, or motd be reflected in title bar
3. just make 'bukkitgui (v2.0.0.245) - Server running' editable

Thank you, this option would be great

**Comment by Bertware** [comment]
I'll implement it :)
