### ISSUE TITLE
Stopping server dialog plugin removal

### ISSUE THREAD

**Issue by technoguy20000** [Bertware/bukkitgui2#45]
When the remove button is clicked in the plugin tab, a dialog appears that asks if you want to stop the server or not. Upon clicking yes, the stopping server dialog appears, and once the status bar says the server is stopped, an error appears:
![error](https://cloud.githubusercontent.com/assets/9159734/5789371/56c94eda-9e2d-11e4-9bc5-63eef0fdbff5.PNG)

The Kill button does nothing at this point, and both the X and Cancel buttons yield the same error. The only way to close the dialog is to force close BukkitGUI itself in task manager.

**Comment by Bertware** [comment]
Hmmm, should've been fixed a few versions ago, I'll check it out
