### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Jonathan8991** [Bertware/bukkitgui2#51]
Im open the program and Apears this

Exception: Fatal el elemento Raiz
Details: En System.Xml.XmlTextReader.Impl.Throw¨(Exception e)
en System.Xml.Xml.TextReaderImpl.Parse DocumentContent()
en System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader
reader, Boolean preserveWhitheSpace
en System.Xml.XmlDocument.Load(XmlReader reader)
en System.Xml.XmlDocument.Load(String filename)
en
Net.BertWare.BukkitGUI2.core.Configuration.config.LoadFile(String
location)
en Net.BertWare.BukkitGUI2.core.Configuration.config.Initialze()
en Net.BertWare.BukkitGUI2.core.Share.Initiallze
en Net.BertWare.BukkitGUI2.core.UI.MainForm..ctor()
en Net.BertWare.BukkitGUI2.core.Launcher.Run()
en Net.BertWare.BukkitGUI2.core.Program.Main(String[] ArgString)

**Comment by Bertware** [comment]
Your config file seems corrupted, try deleting it (found at %appdata%/Bertware/bukkitgui2 )

**Comment by Jonathan8991** [comment]
Thanks
 

     El Sábado, 24 de enero, 2015 18:37:30, Bertware <notifications@github.com> escribió:
   

 Your config file seems corrupted, try deleting it (found at %appdata%/Bertware/bukkitgui2 )—
