### ISSUE TITLE
Send stop command dialog on window close not new style

### ISSUE THREAD

**Issue by technoguy20000** [Bertware/bukkitgui2#56]
Pop-ups on the GUI are colored rectangles that stretch all the way across the screen. The Send stop command dialog on BukkitGUI2 close does not look like the rest.

**Comment by Bertware** [comment]
Update your GUI to the latest release (I uploaded it 20 minutes ago, but only just announced it on the auto updater)

**Comment by technoguy20000** [comment]
Do you mean 2.0.0.274? It's the same.

**Comment by technoguy20000** [comment]
By the way, this is the message box that I meant. I did not see an update available and the latest release seems to have the same issue. Is the official update yet to be released?

![capture](https://cloud.githubusercontent.com/assets/9159734/6090732/ac6f07bc-ae4a-11e4-9dbe-dfb831bc849a.PNG)
.

**Comment by Bertware** [comment]
The update hasn't been pushed to the auto-updater yet. You can download it here: http://dev.bukkit.org/media/files/859/613/bukkitgui.exe
