### ISSUE TITLE
Deleting task does not disable it

### ISSUE THREAD

**Issue by technoguy20000** [Bertware/bukkitgui2#68]
I created a task that stopped the server when someone logged off, and deleted the task after running it once. The task still runs, even though I deleted it.

**Comment by technoguy20000** [comment]
I can no longer replicate this issue in the newest version, so I am assuming it's been resolved.

**Comment by Bertware** [comment]
It's a workaround right now, but it doesn't have a negative impact on performance or resource usage :)

**Comment by technoguy20000** [comment]
What makes this solution a workaround?

**Comment by Bertware** [comment]
As you can see in commit 466407bf30102d671a42d499430b8172254b8c86 , Triggers can't possibly fire after they're disabled due to 
   if (!Enabled) return;
However, I should trace why they don't disable correctly, they shouldn't try to trigger once they're disabled
