### ISSUE TITLE
cauldron not starting

### ISSUE THREAD

**Issue by Jcarr0ndo** [Bertware/bukkitgui2#71]
cauldron for 1.7.10 version: 1.1207.01.198
i am trying to put it to work, i installed the server and the required libraries but when i tried to run it, nothing, i tried the beta version of the bukkitgui and still nothing, it just starts and then, 5 seconds later stops. no crash report, and on the screen it only says starting server and stopped server.

**Comment by Bertware** [comment]
Tested with cauldron 1.7.10 and libraries 1.1388.1.0, working.
Select the cauldron server profile, extract the libraries zipfile in the same folder as cauldron, and run the server.
