### ISSUE TITLE
Spigot: Server starts and stops!

### ISSUE THREAD

**Issue by lucidon** [Bertware/bukkitgui2#73]
Here is my problem!  

[GUI]Starting spigot server - min. RAM:151 - max. RAM:1042
[GUI] The server is starting...
[GUI] Server started...
[GUI] The server has stopped...

**Comment by Bertware** [comment]
There is probably something wrong with the .jar file. Try downloading the file again, and make sure all settings are valid

**Comment by TrevorNewwsome** [comment]
I have the same issue, it seems to be with the Spigot.jar file, but I have tried downloading it and no success. Anyone any ideas?

**Comment by Bertware** [comment]
I'll check out the spigot compatibility once I have some time :)

**Comment by Snipershotmaster** [comment]
Have you tried running the server with CMD, and with thoes arguments?

**Comment by Bertware** [comment]
I ran spigot recently during a GUI stress test, and it worked fine. I used the spigot profile with spigot 1.8.
