### ISSUE TITLE
Backups save to two locations

### ISSUE THREAD

**Issue by nprail** [Bertware/bukkitgui2#81]
Backups save to the specified location as well as:
"C:\Users\Administrator\AppData\Roaming\Bertware\Bukkitgui2\temp"

The problem with this is that the second location is not compressed. I am guessing that it is supposed to save to this folder, compress, then be deleted but it does not do the last step?

**Comment by Bertware** [comment]
it's indeed a temporary file to prepare for compression, and it should be deleted afterwards. I'll check it out
