### ISSUE TITLE
bukkitgui cant find my router error

### ISSUE THREAD

**Issue by joshuacoulter** [Bertware/bukkitgui2#83]
keeps saying something went wrong under port forawading using my public ip but i keeps giving me errors saying it cant find my router is netgear ac1200 r6200 and ill post photo of the error after im done posting this problem

**Comment by joshuacoulter** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13439170/8808702/32e91df8-2fb2-11e5-9de6-f8e1b7fa3e85.png)

**Comment by joshuacoulter** [comment]
im running noip dns software in the background trying to cover my ip up and doing a free spigot server for my friends and i

**Comment by joshuacoulter** [comment]
forget it im buying a ggserver soon

**Comment by joshuacoulter** [comment]
ive tried everything from using other tutorials to using bukkitgui thinking it might help but it doesnt

**Comment by Bertware** [comment]
Looking at the screenshot you provided, it seems your router does not support uPnP, or that uPnP support is disabled in your routers settings. You will need to manually create the port forward entry. How-to's and manuals for your specific router are available online on your router manufacturer's website or can be found using google.
If you are sure your router supports uPnP, you can try bukkitGUI v2.x and see if it fixes the issue. bukkitGUI 2 can be downloaded from http://dev.bukkit.org/bukkit-plugins/bukkitgui/
