### ISSUE TITLE
Bukkitgui2 has stopped working

### ISSUE THREAD

**Issue by SethGandy** [Bertware/bukkitgui2#85]
Just upgraded to windows 10, when I run bukkitgui (v2.0.0.298) it has a "A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is avaliable." error, but it runs just fine. It happens when it hangs up in the begining.

**Comment by Bertware** [comment]
duplicate of #86, it should be fixed now (was a webserver issue, this bug will be fixed in the next update :) )
