### ISSUE TITLE
Bukkitgui2has stopped working

### ISSUE THREAD

**Issue by Bio-Toxic** [Bertware/bukkitgui2#86]
Every time I try to open my bukkitgui2 it says "Bukkitgui2 has stopped working
A problem caused the program to stop working correctly.
Windows will close the program and notify you if a solution is available. I am currently in the process of updating to windows 10
and I noticed that it started after I killed my server.
Is there any solution to this problem? If there is, please let me know.

**Comment by Bertware** [comment]
Can you try again? It should be resolved. Issue was caused by the update server returning a 502 HTTP error, I'll fix this bug in an upcoming update, but in the meanwhile, the server is back online and it should work :)
