### ISSUE TITLE
Bukkit GUI v2.0.0.316 won't run correctly

### ISSUE THREAD

**Issue by connorman82** [Bertware/bukkitgui2#91]
I have tried to launch the latest Bukkit GUI beta but when it loads I get this error.
![screenshot 4](https://cloud.githubusercontent.com/assets/13938729/9556083/a1602f9e-4d97-11e5-9ccb-cd618603f3bd.png)
I press continue and it does absolutely nothing.

**Comment by Bertware** [comment]
What message do you get when expanding details?
What's the contents of your error.log? (found at %appdata%\Bertware\Bukkitgui2\log)
Can you remove the entire %appdata%\Bertware\Bukkitgui2 folder? (it will regenerate by itself when the GUI is ran again)

**Comment by connorman82** [comment]
Deleting the BukkitGUI2 folder seemed to have worked. Thanks so much for the help!

**Comment by Bertware** [comment]
Happy to hear it's working again, looks like one of the config files got corrupted by a previous version
