### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by McSwede** [Bertware/bukkitgui2#94]
The message I get told to give to the developer:

Exception: Could not load type 'Net.Bertware.Bukkitgui2.UI.MainForm' from assembly 'bukkitgui, Version=2.0.0.323, Culture=neutral, PublicKeyToken=null'.
Details: at Net.Bertware.Bukkitgui2.Program.Main () [0x00000] in <filename unknown>:0

This shows up when i try to launch the program. The old BukkitGUI.exe works fine.

**Comment by Bertware** [comment]
Hi, can you get the log file, found at 
%appdata%\Bertware\Bukkitgui2\log\bukkitgui.log ? 
I suggest you upload the contents to pastebin.com or some similar service.

After you get the message, can you still use the GUI?

**Comment by McSwede** [comment]
http://pastebin.com/t08V6k4w
And no the GUI never starts.

**Comment by Bertware** [comment]
Your log doesn't contain any abnormal information. Try downloading the file again, and if it doesn't help, try installing .NET again. You can find the .NET framework here: http://download.microsoft.com/download/6/0/f/60fc5854-3cb8-4892-b6db-bd4f42510f28/dotnetfx35.exe

**Comment by Bertware** [comment]
Closed due to inactivity / not caused by GUI code but due to NET framework issues.
