### ISSUE TITLE
Rename server uptime to elapsed server uptime

### ISSUE THREAD

**Issue by mcsnetworks** [Bertware/bukkitgui2#95]
How do I setup a re-occurring task using the 2.0.x version of Bukkit GUI.

The old version had this ability but I can't figure out how to do it in 2.0

Thanks,

**Comment by Bertware** [comment]
You can either use "server uptime" which will run every x time the server has been running (eg every 10 minutes, do ... ), or you can use the current time trigger to let something run daily at a given time.

**Comment by mcsnetworks** [comment]
Is there a reason why you remove "re-occurring task" ?

**Comment by Bertware** [comment]
What is the exact name of the trigger you're talking about? If you want to run something every x time, you can use server uptime. It's the same as elapsed time in v1, only renamed.

**Comment by mcsnetworks** [comment]
Ok, then please rename it as Re-Occurring, because in theory, if the server is running 00:30:00 minutes then the general feeling is that it will only hit that trigger once because until the server is restarted then it will never hit the 00:30:00 trigger again.

Thoughts?

**Comment by Bertware** [comment]
It was renamed since to make clear it only runs when the server is actually running. However, if the new name causes confusion, it should be changed again. Elapsed server uptime maybe?

**Comment by mcsnetworks** [comment]
Elapsed indicated time from which the server was started, doesn't state anything about re-occurring.

**Comment by Smiley43210** [comment]
I agree; I was under the assumption that the server uptime trigger only ran once - upon reaching that time.
