### ISSUE TITLE
Saving a task without selecting an action will cause big issues

### ISSUE THREAD

**Issue by mcsnetworks** [Bertware/bukkitgui2#96]
Ok, while playing around with 2.0, I discovered that if you some how manage to get a "Tasker" task to save without specifying an action the entire tasker tab breaks down.

If you close the BukkitGUI executable and re-launch then the tasker tab doesn't even appear within the application.

I fixed this by modifying the tasklist file and removing the task that didn't have an action specified.

I would suggest sanitizing your save(s) and making sure it cannot save a task without a action OR handle the exception thrown when a task doesn't have a action better.

P.S. thanks for all your hard work.

**Comment by Bertware** [comment]
I'll look at it, this shouldn't be possible indeed :)

**Comment by Bertware** [comment]
Fixed it! Fix will be included in the next release
