### ISSUE TITLE
EULA

### ISSUE THREAD

**Issue by Arctic-JD** [Bertware/bukkitgui2#97]
![image](https://cloud.githubusercontent.com/assets/9632926/9838861/7cffad9e-5a2d-11e5-9b90-ca31099e73b7.png)

I can't seem to start my sever, the EULA is set to true, but it won't allow me to start the server.

**Comment by Bertware** [comment]
The server runs in the GUI folder. is there a eula.txt file in the folder where the GUI is located?

**Comment by Arctic-JD** [comment]
@Bertware Not that I know of.

**Comment by Arctic-JD** [comment]
@Bertware Fixed it, sorry, I can be somewhat dumbfounded sometimes. I didn't put the program in it's own folder.
